version: "3.9"

services:
  db:
    image: postgres:15
    container_name: task_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    # Uncomment ONLY if you want DB access from host
    # ports:
    #   - "5432:5432"

  backend:
    build: .
    container_name: task_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/task_manager

volumes:
  postgres_data:




